name: test_action

on:
  repository_dispatch:
    types: [trigger-workflow]
  push:
    branches:
      - main
#  pull_request:
  workflow_dispatch:


jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
         touch mad.txt
         echo hello
         chmod +x script.sh
         echo world
         ./script.sh
      - name: Trigger Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          repository: madcloudeq/cross-repo-trigger
          event-type: trigger-workflow



#  ping-pong:
#    runs-on: ubuntu-latest
#    steps:
#      - name: PING - Dispatch initiating repository event
#        if: github.event.action != 'pong'
#        run: |
#          curl -X POST https://api.github.com/repos/madcloudeq/cross-repo-trigger/dispatches \
#          -H 'Accept: application/vnd.github.everest-preview+json' \
#          -u ${{ secrets.ACCESS_TOKEN }} \
#          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
#      - name: ACK - Acknowledge pong from remote repository
#        if: github.event.action == 'pong'
#        run: |
#          echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
#          curl -X POST https://api.github.com/repos/madcloudeq/cross-repo-trigger/dispatches \
#          -H 'Accept: application/vnd.github.everest-preview+json' \
#          -u ${{ secrets.ACCESS_TOKEN }} \
#          --data '{"event_type": "ack", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
